#ifndef __ExecPairSpectra_H__
#define __ExecPairSpectra_H__

// External Includes
#include "ExecBase.h"
#include "ParameterList.h"
#include "DelimitedTextReader.h"
#include "FalseLocalizationRates.h"
#include "PeptideSpectrumMatch.h"
#include "SpectrumLibrary.h"
#include "spectrum.h"
#include "utils.h"
#include "FileLoadingUtils.h"

// Module Includes
#include "Logger.h"
#include "FileUtils.h"

// System Includes
#include <stdio.h>
#include <string>
#include <vector>

//TR1 includes. GCC 4.0 and above only!
#ifdef __GLIBCXX__
#  include <tr1/unordered_set>
#  include <tr1/unordered_map>
#else
#  ifdef __IBMCPP__
#    define __IBMCPP_TR1__
#  endif
#  include <unordered_set>
#  include <unordered_map>
#endif

namespace specnets
{
  /*! \brief Class to pair modified and unmodified spectra
   */
  class ExecPairSpectra : public ExecBase
  {
  public:
    //! \name CONSTRUCTORS
    //@{
    /*! \brief The exemplar constructor.

     Generally this constructor should not be used. It is only used by the
     module execution factory in order to create an exemplar object (without
     valid parameters) which is then used to create a real (valid) object
     using the clone() method.
     @sa clone()
     */
    ExecPairSpectra(void);

    /*! \brief The default constructor

     This is the default constructor. A valid set of parameters must be
     supplied in the input parameter. The parameters can then be verified
     using the validateParams() method.
     @sa validateParams()
     @param inputParams structure containing all input parameters necessary for execution
     */
    ExecPairSpectra(const ParameterList & inputParams);

    /*! \brief Constructor which takes both the parameters and the data structures

     Constructor which takes both the parameters and the data structures necessary for
     generating svm scores. When using this constructor no external data need be read in.
     The parameters can be verified using the validateParams() method.
     @sa validateParams()
     */
    ExecPairSpectra(const ParameterList & inputParams,
                    PeptideSpectrumMatchSet * peptideResults,
                    SpecSet * specSet);
    //@}

    //! \name DESTRUCTOR
    //@{
    virtual ~ExecPairSpectra(void);
    //@}

    //! \name ACCESSORS
    //@{
    /*! \brief Creates a new module of the virtual class with the given params.

     The parameters should be sufficient for the derived class to be invoked properly.

     @return A pointer to the newly created object
     */
    virtual ExecBase * clone(const ParameterList & inputParams) const;

    //! \name MODIFIERS
    //@{
    /*! \brief Executes the module.

     In order to call this method succesfully all the necessary data for
     execution must already be loaded into memory (data members). This can
     be accomplished using the loadInputData() method.

     @return True if execution finished successfully, false otherwise.
     @sa loadInputData()
     */
    virtual bool invoke(void);

    /* \brief separates m_peptideResults into modified and
     * unmodified psms
     *
     * @param modifiedSpectra - output for modified spectra
     * @param unmodifiedSpectra - output for unmodified spectra
     */
    void separateModUnmod(PeptideSpectrumMatchSet &modifiedSpectra,
                          SpectrumLibrary &unmodifiedSpectra,
                          int unmodMsLevel,
                          bool isUniqueUnmodified);

    /*! \brief Loads the input data from the files specified in the params.

     Loads all the data from files into the data members. This method is
     primarily used by the execution module to load necessary data when
     executing in a separate process..

     @return True if data was loaded successfully, false otherwise.
     @sa ExecPairSpectra(const ParameterList & input_params), saveOutputData()
     */
    virtual bool loadInputData(void);

    /*! \brief Saves all the result data to files specified in the params.

     Saves all the result data generated by the module to files specified
     by values in the params. This is used to either save the data permanantly,
     or to be loaded back in after remote execution is finished and results
     need to be merged by the merge() method.

     @param filenames A list of file names that contain the data necessary to run the module
     @return True if data was saved successfully, false otherwise.
     @sa ExecPairSpectra(const ParameterList & input_params), loadInputData(), merge()
     */
    virtual bool saveOutputData(void);

    /*! \brief Saves all the internal data into files specified in the params.

     Saves all the data required for an external process to execute the
     module. The external process would call loadInputData() to reload the
     data into the members before calling invoke(). The user passes a vector
     that will contain the names of all files necessary to run the module as
     a separate process. The first file in this list will always be the main
     parameter file.

     @param filenames A list of file names that contain the data necessary to run the module
     @return True if data was saved successfully, false otherwise.
     @sa ExecPairSpectra(const ParameterList & input_params), loadInputData()
     */
    virtual bool saveInputData(std::vector<std::string> & filenames);

    /*! \brief Loads the output data from the files specified in the params.

     Loads all the data from output files into the data members. The purpose
     of this is to ready "child" modules to be merged back together after
     being executed separately.

     @return True if data was loaded successfully, false otherwise.
     @sa ExecPairSpectra(const ParameterList & input_params), saveOutputData()
     */
    virtual bool loadOutputData(void);

    /*! \brief Splits the module into multiple "children" for parallel execution.

     Divides the work required by the module into a vector of sub-modules
     that can be executed in parallel (by the the ParallelExecution() class.
     The split method should divide the work into "nodes" and sub-divide into
     "cpus" for each node. Because the precise implementation of parallel execution
     is not known apriori, nodes may be thought of as large batches, while the
     number of CPUs can be thought of as modules which will be run simultaneously
     within those batches. For example, split may be called with numNodes = 1
     and numCpus = 4 on a quad-processor machine to prep for a threaded implementation.
     Or it may be called with numNodes = 4 and numCpus = 1 to prepare for
     distributed execution on 4 separate machines on a network.

     @param numNodes Number of separate nodes
     @param numCpus Number of CPUs per node
     @return The set of sub-modules (children) that the original module has been split into.
     An empty vector implies an error.
     @sa merge()
     */
    virtual std::vector<ExecBase *> const & split(int numSplit);

    /*! \brief Merges the child modules back into a complete result

     This method is only called when split is used for parallel execution
     and after the execution of all children has been completed. This method
     will merge the results generated by each of the child modules into
     one cohesive result as if the module had been run as a single entity.

     @return True if merge could be performed successfully, false otherwise.
     @sa split(int numNodes, int numCpus)
     */
    virtual bool merge(void);

    /*! \brief Performs validation of the input parameters.

     Checks the parameters structure provided in the constructor to see if they
     are sufficient and correct to invoke the module. Also sets the internal
     validity flag so that isValid() will return the correct result.

     @param error A description of the error (if any occurs)
     @return True if the parameters for the module are valid, false otherwise.
     @sa isValid()
     */
    virtual bool validateParams(std::string & error);
    /*! \brief Performs validation of the input parameters if we're generating statistics in module.

     Checks the parameters structure provided in the constructor to see if they
     are sufficient and correct to invoke the module. Also sets the internal
     validity flag so that isValid() will return the correct result.

     @param error A description of the error (if any occurs)
     @return True if the parameters for the module are valid, false otherwise.
     @sa isValid()
     */
    bool validateStatisticsParams(std::string & error);

    static bool loadSpecSet(string & path, string & fileExt, SpecSet & currSet);

    static bool loadInspectSpectrum(const char * specSetListFile,
                                    PeptideSpectrumMatchSet &psms,
                                    SpecSet &otuputResults);


    //@}

  private:
    bool ownInput; //! Does this object "own" the input data pointers (and hence have to free them)

    PeptideSpectrumMatchSet * m_peptideResults;
    SpecSet * m_specSet; //! Maps between specset file name and specset.
    bool ownOutput; //! Does this object "own" the output data pointers (and hence have to free them)
    MS2ScoringModel m_modelLP; //! MS2 scoring model used for LP formation
    MS2ScoringModel m_model; //! MS2 scoring model used for statistics to filter spectra
    vector<string> m_extractedIons; //! ions to include when calculating cosine
    vector<float> m_modifications; //! vector of modifications we're calculating FLR on
    vector<vector<float> > m_massShifts; //! vector of mass shifts corresponding to the m_modifications spectra (i.e., -18 for phosphorylation modifications)
    vector<float> m_fixedMods; //! Mods for which we won't shift position (SILAC for unmodified spectra in Phospho data)

  };

} // namespace specnets

#endif // __ExecPairSpectra_H__
