#ifndef __ExecPrmScoring_H__
#define __ExecPrmScoring_H__

// Module Includes
#include "ExecBase.h"
#include "ExecMergeConvert.h"

// External Includes
#include "spectrum.h"
#include "SpecSet.h"
#include "ClusterSet.h"
#include "db_fasta.h"
#include "PeptideSpectrumMatchSet.h"

// System Includes
#include <string>
#include <vector>

using namespace std;

namespace specnets
{

  class ExecMergeConvert;

  /*! \brief Execution class for spectrum alignment

   \todo Have Nuno add a more detailed description
   */
  class ExecPrmScoring : public ExecBase
  {
  public:
    //! \name CONSTRUCTORS
    //@{
    /*! \brief The exemplar constructor.

     Generally this constructor should not be used. It is only used by the
     module execution factory in order to create an exemplar object (without
     valid parameters) which is then used to create a real (valid) object
     using the clone() method.
     @sa clone()
     */
    ExecPrmScoring(void);

    /*! \brief Constructor which takes only the set of parameters

     Constructor which takes only the set of parameters required to execute the
     module. The parameters specify all data files for input and output, and requires
     that the user call loadInputData() in order to read all data from files into
     the members of the object. The parameters can be verified using the
     validateParams() method.
     @sa validateParams()
     @param inputParams structure containing all input parameters necessary for execution
     */
    ExecPrmScoring(const ParameterList & inputParams);

    /*! \brief Constructor which takes both the parameters and the data structures

     Constructor which takes both the parameters and the data structures necessary for
     executing the alignment. When using this constructor no external data need be read in.
     The parameters can be verified using the validateParams() method.
     @sa validateParams()
     @param inputSpectra The set of input spectra to be aligned
     @param outputSpectra The set of input spectra to be aligned
     */
    ExecPrmScoring(const ParameterList & inputParams,
                   SpecSet * inputSpectra,
                   ClusterSet * inputClusters,
                   SpecSet * outputSpectra,
                   ClusterSet* outputClusters);

    ExecPrmScoring(const ParameterList & inputParams,
                   SpecSet * outputSpectra,
                   ClusterSet* outputClusters);

    //@}

    //! \name DESTRUCTOR
    //@{
    virtual ~ExecPrmScoring(void);
    //@}

    //! \name ACCESSORS
    //@{
    /*! \brief Creates a new module of the virtual class with the given params.

     The parameters should be sufficient for the derived class to be invoked properly.

     @return A pointer to the newly created object
     */
    virtual ExecBase * clone(const ParameterList & input_params) const;

    //@}

    //! \name MODIFIERS
    //@{
    /*! \brief Executes the module.

     In order to call this method succesfully all the necessary data for
     execution must already be loaded into memory (data members). This can
     be accomplished using the loadInputData() method.

     @return True if execution finished successfully, false otherwise.
     @sa loadInputData()
     */
    virtual bool invoke(void);

    /*! \brief Loads the input data from the files specified in the params.

     Loads all the data from files into the data members. This method is
     primarily used by the execution module to load necessary data when
     executing in a separate process..

     @return True if data was loaded successfully, false otherwise.
     @sa ExecBase(const ParameterList & input_params), saveOutputData()
     */
    virtual bool loadInputData(void);

    /*! \brief Saves all the result data to files specified in the params.

     Saves all the result data generated by the module to files specified
     by values in the params. This is used to either save the data permanantly,
     or to be loaded back in after remote execution is finished and results
     need to be merged by the merge() method.

     @param filenames A list of file names that contain the data necessary to run the module
     @return True if data was saved successfully, false otherwise.
     @sa ExecBase(const ParameterList & input_params), loadInputData(), merge()
     */
    virtual bool saveOutputData(void);

    /*! \brief Saves all the internal data into files specified in the params.

     Saves all the data required for an external process to execute the
     module. The external process would call loadInputData() to reload the
     data into the members before calling invoke().

     @param filenames A list of file names that contain the data necessary to run the module
     @return True if data was saved successfully, false otherwise.
     @sa ExecBase(const ParameterList & input_params), loadInputData()
     */
    virtual bool saveInputData(std::vector<std::string> & filenames);

    /*! \brief Loads the output data from the files specified in the params.

     Loads all the data from output files into the data members. The purpose
     of this is to ready "child" modules to be merged back together after
     being executed separately.

     @return True if data was loaded successfully, false otherwise.
     @sa ExecBase(const ParameterList & input_params), saveInputData()
     */
    virtual bool loadOutputData(void);

    /*! \brief Splits the module into multiple "children" for parallel execution.

     Divides the work required by the module into a vector of sub-modules
     that can be executed in parallel (by the the ParallelExecution() class.

     @param numSplit Number of separate modules to split into
     @return The set of sub-modules (children) that the original module has been split into.
     An empty vector implies an error.
     @sa merge()
     */
    virtual std::vector<ExecBase *> const & split(int numSplit);

    /*! \brief Merges the child modules back into a complete result

     This method is only called when split is used for parallel execution
     and after the execution of all children has been completed. This method
     will merge the results generated by each of the child modules into
     one cohesive result as if the module had been run as a single entity.

     @return True if merge could be performed successfully, false otherwise.
     @sa split(int numSplit)
     */
    virtual bool merge(void);

    /*! \brief Performs validation of the input parameters.

     Checks the parameters structure provided in the constructor to see if they
     are sufficient and correct to invoke the module. Also sets the internal
     validity flag so that isValid() will return the correct result.

     @param error A description of the error (if any occurs)
     @return True if the parameters for the module are valid, false otherwise.
     @sa isValid()
     */
    virtual bool validateParams(std::string & error);
    //@}

  protected:

    virtual bool invokePepNovoCID(ParameterList& params,
                                  SpecSet& inputSpectra,
                                  SpecSet& outputSpectra,
                                  vector<vector<bool> >* reversedPeaks = 0);

    virtual bool invokePepNovoHCD(ParameterList& params,
                                  SpecSet& inputSpectra,
                                  SpecSet& outputSpectra,
                                  vector<vector<bool> >* reversedPeaks = 0);

    virtual bool invokePepNovoETD(ParameterList& params,
                                  SpecSet& inputSpectra,
                                  SpecSet& outputSpectra,
                                  vector<vector<bool> >* reversedPeaks = 0);

    /**
     * Saves input spectra and calls PepNovo with specified parameters
     * @return true if PepNovo completed successfully, false if not
     */
    virtual bool invokePepNovo(ParameterList& params,
                               SpecSet& inputSpectra,
                               SpecSet& outputSpectra,
                               vector<vector<bool> >* reversedPeaks);

    virtual void setOriginMasses(Spectrum* prmSpec,
                                 vector<bool>* reversedPeaks,
                                 Spectrum* ms2Spec,
                                 vector<string>* prmOriginPeaks);

    virtual void setOriginTolerances(Spectrum* prmSpec,
                                     Spectrum* ms2Spec,
                                     vector<string>* prmOriginPeaks);

    /**
     * Given a set of MS/MS spectra with correspnding PRM spectra, this will boost PRMs
     *  in all pairs of spectra with precursors offset by the SILAC heavy/light K/R mod and whose
     *  MS/MS spectra have a an acceptable cosine similarity
     * @param inOutSpecs set of input PRM spectra, which will hold the set of output PRMs as well
     * @param ms2Spectra set of corresponding MS/MS spectra
     * @param inPairedScans set of paired or triplet spectra that should be clustered regardless of their similarity
     * @param outClusteredScans output set of clustered spectra
     */
    virtual void
    boostSilacPairs(SpecSet* inOutSpecs,
                    SpecSet* ms2Spectra,
                    vector<vector<unsigned int> >& inClusteredScans,
                    vector<vector<unsigned int> >& outClusteredScans);

    /**
     * Clusters a set of PRM spectra using overlapping score as a similarity function
     * @param inOutSpecs ptr to set of input spectra, which will be replaced by the set of clustered spectra
     * @param inPairedScans set of paired or triplet spectra that should be clustered regardless of their similarity
     * @param outClusteredScans output set of clustered spectra
     * @return
     */
    virtual void
    mergeSamePrecursorStaged(SpecSet* inOutSpecs,
                             vector<vector<unsigned int> >& inPairedScans,
                             vector<vector<unsigned int> >& outClusteredScans,
                             bool mergeSamePrec,
                             int clusterMinSz,
                             vector<vector<bool> >* reversedPeaks = 0);

    virtual void checkSpecset(SpecSet &inOutSpecs);

  private:
    bool ownInput; //! Does this object "own" the input data pointers (and hence have to free them)
    SpecSet * m_inputSpectra;
    ClusterSet * m_inputClusters;

    bool ownOutput; //! Does this object "own" the output data pointers (and hence have to free them)
    SpecSet * m_outputSpectra;
    ClusterSet * m_outputClusters; //! If clustering PRM spectra, this is the set of output clusters

    vector<pair<unsigned int, unsigned int> > m_scanToIdx;
    vector<unsigned int> m_scanToInputScan;

    bool enforceDaTolerance;
  };

} // namespace specnets

#endif // __ExecPrmScoring_H__
